name: "CI - PyTest "

env:
  SERVER: production
  
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Environment Setup
        run: $Env:PYENV=$pwd.path/pyenv-win
      - name: Environment Setup - 1
        run: Set-Item -Path Env:Path -Value ("$Env:PYENV/bin;$Env:PYENV/shims;" + $Env:Path)
      - name: Environment Setup - 2
        run: pyenv --version
        shell: bash
    
