name: "CI - PyTest "

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Environment Setup
      - run: export PYENV=${{ github.action_path }}/pyenv-win
        shell: bash
      - run: PATH="$PYENV/bin:$PYENV/shims:$PATH"
        shell: bash
      - run: pyenv --version
        shell: bash
    
